services:
  php-app:
    build: .
    depends_on:
      - adminer
      - db
    env_file:
      - ./.env
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html

  adminer:
    image: adminer
    ports:
      - "8090:8080"

  db:
    image: mysql:9.1
    env_file:
      - ./.env

